### ISSUE TITLE
questions about selecting and generating candidates

### ISSUE THREAD

**Issue by wanna-fly** [MuchHair/PD-Net#1]
Hi, thanks for your nice code！
I am trying to use [faster rcnn](https://github.com/SherlockHolmes221/pytorch-faster-rcnn) to get boxes, as described in your guidance. But when I run `python -m lib.data_process_vcoco.select`, there is an FileNotFoundError saying that 

> 'No such file or directory: 'data/vcoco/faster_rcnn_boxes/train_226162_labels.npy'

It seems that running the script in this [repo](https://github.com/SherlockHolmes221/pytorch-faster-rcnn) will only generate 3 files for each image, {global_id}_boxes.npy, {global_id}_scores.npy and {global_id}_nms_keep_indices.json, not including the {global_id}_labels.npy.
So what is the {global_id}_labels.npy supposed to be? what is the shape and content of it?

**Comment by SherlockHolmes221** [comment]
We fix a bug and update select.py. Please try again and  if you have more questions please leave an issue.

**Comment by wanna-fly** [comment]
Thanks! It works now!
