### ISSUE TITLE
Questions about the dataset split

### ISSUE THREAD

**Issue by wanna-fly** [MuchHair/PD-Net#2]
Hi, guys! 
Thanks for your job and this repo is really helpful. But I found that there was a discrepancy between the official dataset split ids and those provided by this repo. In the official annotation files there are 2533 images for training, 2867 images for validating and 4946 images for testing. But in your annotation file(`/vcoco_processed/split_ids.json` ),  there are only 2336 samples for training, 2635 samples for validating and 4539 samples for testing. 
Could you please fix this? Thanks a lot!

**Comment by SherlockHolmes221** [comment]
We follow iCAN, TIN and PMF, our dataset split is the same as theirs for fair comparison

**Comment by wanna-fly** [comment]
> We follow iCAN, TIN and PMF, our dataset split is the same as theirs for fair comparison

Thanks for your reply. 
Yeah you are right,  these works share the same dataset split strategy exactly. But I am still confused that why not just use all the trainval images to train the network and then run detector on the whole test images? This might lead to a better performance. (since the image_ids of ground truth are loaded from the official annotation file during the evaluation)
I've checked these images which are not included in the `split_id.json` and I guess that maybe there is no annotated human-object interaction in these images so the previous work just ignore them during the training and testing. But I am not really sure. It's so kind of you if you can inform me the reason( if you have any idea about it).
Thanks again and I'll close this issue.

**Comment by SherlockHolmes221** [comment]
Yes, The image without gt will be ignored.
